### ISSUE TITLE
PA3 仙剑奇侠传只能显示首页

### ISSUE THREAD

**Issue by hust-nj** [niuyinmei/ICS2018#2]
PA3该界面后无法进入下一界面。
![image](https://user-images.githubusercontent.com/27663478/71864503-e77fd480-313a-11ea-9bf3-87a5aec5c4a6.png)

**Comment by niuyinmei** [comment]
是的，我也遇到了这样的问题。
我偶尔能够进入新的故事，跳出“李大娘blah blah blah”。
（我记得）姚杰老师告诉我之前有学生碰到这样的问题，是因为PA2指令没有按照操作数的长度分别实现。
我当时后剩的时间不多了也没debug下去。
Good Luck！
